codecov:
  token:  03230181-dc42-4e8c-b1f6-46699ee5d066 # Your private repository token
  branch: master  # override the default branch
  bot: CiaranWelsh  # set user whom will be the consumer of oauth requests
  ci:  # Custom CI domains if Codecov does not identify them automatically
    - travis.org

coverage:
  precision: 2  # 2 = xx.xx%, 0 = xx%
  round: nearest # default down
  range: 60...95 # default 70...90. red...green

  notify:

    email:
      default:
        to:
          - cwelsh2@uw.edu
          - &author
        threshold: 1%
        only_pulls: false
        layout: header, diff, trends
        flags: null
        paths: null
  status:
    project:
      default:
        against: parent
        target: auto
        threshold: 1%
        branches:
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

    patch:
      default:
        against: parent
        target: 80%
        branches: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

    changes:
      default:
        against: parent
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

  flags:
    integration:
      branches:
        - master
      ignore:
        - app/ui

  ignore: # files and folders for processing
    - tests/*
    - src/redland/raptor2-2.0.15/**/*
    - src/redland/rasqal-0.9.33/**/*
    - src/redland/redland-1.0.17/**/*
    - src/redland/RedlandAPIWrapper/test/*
    - third_party/**/*

comment:
  layout: header, diff, trends, uncovered
  branches:
    - master
  behavior: default # defualt = posts once then update, posts new if delete
                    # once = post once then updates
                    # new = delete old, post new
                    # spammy = post new

  #codecov:
#  token: 03230181-dc42-4e8c-b1f6-46699ee5d066
#  ci:
#    - "https://travis-ci.org/github/sys-bio/libOmexMeta"
#  strict_yaml_branch: "master"
#coverage:
#  precision: 2
#  round: nearest
#  range: "70...100"
#  status:
#    project:
#      default:
#        threshold: 2%
#    patch:
#      default:
#        target: 80%
# gcov:
#    branch_detection:
#      conditional: yes
#      loop: yes
#      method: no
#      macro: no
#ignore:
#  - "test"  # ignore folders and all its contents
#  - "src/raptor2-2.0.15"
#  - "src/rasqal-0.9.33"
#  - "src/redland-1.0.17"
#  - "src/redland-wrapper-tests/test"
#  - "materials"
#  - "install-msvc"
#  - "install_ubuntu"
#  - "third_party"
#  - "build"
#  - "cmake"
#  - "cmake-build-release-visual-studio"
#  - "cmake-build-release-wsl-ubuntu1804-gcc101"
#  - "Design"
#  - "dist"
#  - "docs"
#comment:
#  layout: "diff"
#
