language: cpp
compiler:
  - gcc
sudo: required
services:
  - docker
dist: bionic
before_install:
  - docker pull ciaranwelsh/libomexmeta-build-env:latest
  - docker run -ti ciaranwelsh/libomexmeta-build-env:latest
install:
  - cd ${TRAVIS_BUILD_DIR}
  - install_prefix="${TRAVIS_BUILD_DIR}/libOmexMeta/install-docker"
  - git clone https://github.com/sys-bio/libOmexMeta.git
  - cd libOmexMeta && mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX="$install_prefix" -DVCPKG_ROOT="/vcpkg" ..
  - make -j 8 \
  - make install
script:
  - make ctest
#  - ${HOME}/install/bin/OmexMetaTests
#  - ${HOME}/install/bin/redland-wrapper-tests
  - conda activate omex
after_success:
#  - nosetests ${HOME}/libOmexMeta/tests/python
  - make TestCoverageHtml
  - make TestCoverageXml
  - cp /home/travis/docs-build/sys-bio/libOmexMeta/docs-build/TestCoverageXml.xml /home/travis/docs-build/sys-bio/libOmexMeta/docs-build/coverage.xml
#  - codecov # submit coverage : for python. No work.
  - gcovr -r .. -v  -e ${TRAVIS_BUILD_DIR}/src/redland/RedlandWrapperAPI/test --html-details --json-pretty {TRAVIS_BUILD_DIR}/src/omexmeta ${TRAVIS_BUILD_DIR}/src/omexmeta ${TRAVIS_BUILD_DIR}/src/redland/RedlandWrapperAPI/
  - bash <(curl -s https://codecov.io/bash) -t 03230181-dc42-4e8c-b1f6-46699ee5d066 -R /home/travis/docs-build/sys-bio/libOmexMeta
  - coveralls --exclude tests --gcov-options '\-lp' -r ${TRAVIS_BUILD_DIR} -b ${TRAVIS_BUILD_DIR}/docs-build -i ${TRAVIS_BUILD_DIR}/docs-build/src/omexmeta/ -i ${TRAVIS_BUILD_DIR}/docs-build/src/redland/RedlandWrapper -e ${TRAVIS_BUILD_DIR}/docs-build/src/redland/RedlandWrapper/test -t LIcCj7cYF1DBxqHO80fauUQCiKkSsfBfC


#An example travis file : https://github.com/hpnog/computingProblems/blob/master/.travis.yml