name: pyomexmeta
dependencies:
  - win32api [platform startswith win]
  - breathe
  - sphinx-tabs
  - recommonmark
  - beautifulsoup4
  - requests
  - sphinxcontrib-programoutput
  - tellurium
  - python-libcombine
  - pytest